name: CI

on:
  push:
    branches:
    - 'main'
    - 'release-*'
  pull_request:
    types: 
    - opened
    - reopened
    - synchronize

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@6b3083af2869dc3314a0257a42f4af696cc79ba3 # v2.3.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            uploads.github.com:443
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          fetch-depth: 0
      - name: Echo Stuff
        run: |
          echo "${{ github.ref }}"
          echo "${{ github.ref_name }}"
          echo "${{ github.ref_type }}"
          echo "${{ github.base_ref }}"
          echo "${{ github.head_ref }}"
          echo "${{ github.event.pull_request.base.ref }}"
          echo "${{ github.event.pull_request.head.repo.full_name }}"
          echo "${{ github.repository }}"
          echo "${{ github.event.pull_request.head.repo.fork }}"
      - name: Is a fork
        if: "github.event.pull_request.head.repo.fork"
        run: |
          echo "This is a fork"
      - name: Is not a fork
        if: "!github.event.pull_request.head.repo.fork"
        run: |
          echo "This is not a fork"
      - name: Is not a fork and not branch name release
        if: ${{ !startsWith(github.ref_name, 'release-') && !github.event.pull_request.head.repo.fork }}
        run: |
          echo "This is not a fork & not a release branch"
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0